#!/bin/bash

if test ! -n "$LOGMATIC_TOKEN"; then
   echo 'LOGMATIC_TOKEN is required!'
   exit 1
fi

if test ! -n "$LOGMATIC_HOSTNAME"; then
    echo "LOGMATIC_HOSTNAME not defined, using `hostname`"
    export LOGMATIC_HOSTNAME='%HOSTNAME%'
fi

export LOGMATIC_TAGS=`echo $LOGMATIC_TAGS | sed -e s,'"','\\\\\\\"',g`

sed -e s,__LOGMATIC_TOKEN__,"$LOGMATIC_TOKEN",g \
    -e s,__LOGMATIC_TAGS__,"$LOGMATIC_TAGS",g \
    -e s,__LOGMATIC_HOSTNAME__,"$LOGMATIC_HOSTNAME",g \
    /rsyslog-logmatic.tmpl > /etc/rsyslog.d/50-logmatic.conf

exec /usr/sbin/rsyslogd -n
